---
lightbox: true
execute:
  echo: false
---

# About this Workshop {.unnumbered}

The [Shiny](https://shiny.posit.co/){target="_blank"} R package is over ten years old and is a popular tool to create immersive, web-based content. Although many water quality scientists and professionals have experience with R, expertise in dashboards is uncommon. This workshop will introduce the fundamentals of building Shiny dashboards in R using real-world examples with hands-on coding exercises. The benefits of developing Shiny dashboards and their potential applications to improve research, monitoring, and management will be discussed. Special attention will be on the merits of open source software for creating reproducible and transparent dashboard workflows, including addressing common deployment and IT hurdles. Attendees are strongly encouraged to bring their own laptops to follow along with the workshop exercises. Anyone interested in learning how to expand existing R skills for dashboard development will benefit from this workshop. This includes student, early career, and advanced professionals from any employment sector and field of expertise.

## Agenda {.unnumbered}

```{r}
load(file = 'data/agenda.RData')
knitr::kable(agenda)
```

## Important links {.unnumbered}

* Workshop Website: [link](https://tbep-tech.github.io/nwqmc-shiny){target="_blank"}
* Kickoff Menti: [Link](https://www.menti.com/al8cgs1ouubx){target="_blank"}
* Live Coding: [Link](https://tinyurl.com/live-nwqmc-shiny){target="_blank"}
* Live Chat: [link](https://app.gitter.im/#/room/#nwqmc-shiny:gitter.im){target="_blank"}
* Posit Cloud: [link](https://posit.cloud/content/9569756){target="_blank"}
* Post-workshop survey: [link](https://forms.gle/868MnzAQRj4XH4t56){target="_blank"}

## Housekeeping {.unnumbered}

Please read these housekeeping items on the day of the training so that everything runs smoothly. 

1. Feel free to verbally ask questions during the training.  You can also type questions in the [live chat](https://app.gitter.im/#/room/#nwqmc-shiny:gitter.im){target="_blank"}.  Other attendees are welcome to respond to questions in the chat.  

1. Please use [Posit Cloud](https://posit.cloud/content/9569756){target="_blank"}) or RStudio installed on your computer to follow along during the workshop.  RStudio Cloud can also be used as a backup option.  See the [setup](setup.qmd) instructions for more information.

1. We have a [live coding](https://tinyurl.com/live-ebase){target="_blank"} link that we’ll be using as we go through the lessons. If you get lost, you can copy/paste code from this link into RStudio.

1. All training content is on this website. If you get lost you can view the agenda to see which lesson we’re covering.

## Setup {.unnumbered}

Please visit the [setup](setup.qmd) page for instructions on participating during this workshop. You can use an RStudio project on Posit Cloud setup specifically for this workshop.  You may also use your own local version of R and RStudio if preferred.

We also expect some prior experience using R. Please visit the [intro to R](rintro.qmd) page for a quick crash course.

## Presenters {.unnumbered}

### Marcus Beck

Dr. Marcus Beck is the Senior Scientist for the Tampa Bay Estuary Program in St. Petersburg, Florida and is developing data analysis and visualization methods for Bay health indicators. Marcus has experience researching environmental indicators and developing open science products to support environmental decision-making. He has been using the R statistical programming language for over 15 years and has taught several workshops on its application to environmental sciences. Marcus has also developed several R packages and currently maintains 7 on CRAN. He received a PhD in Conservation Biology with a minor in Statistics from the University of Minnesota in 2013, his Masters in Conservation Biology from the University of Minnesota in 2009, and his Bachelors in Zoology from the University of Florida in 2007. [GitHub](https://github.com/fawda123){target="_blank"}, [Scholar](https://scholar.google.com/citations?user=9ZDDQ_8AAAAJ&hl=en&authuser=2){target="_blank"}, [CV](https://github.com/fawda123/CV/blob/master/Beck_CV.pdf){target="_blank"}

### Erik Leppo

Erik W. Leppo is an environmental scientist and data scientist based in Maryland. He has been working with Tetra Tech since 1994, focusing on environmental data analysis and biomonitoring. Erik has extensive experience with R programming since 2006 and has been developing Shiny applications since 2017. He is also active on GitHub, where he shares various tools for biomonitoring and bioassessment.  He maintains the baytrends package on CRAN.  He has led or helped run several R workshops and discussions at both the Association of Mid-Atlantic Aquatic Biologists (AMAAB) and the National Water Quality Monitoring Council (NWQMC) conference. [GitHub](https://github.com/leppott){target="_blank"}
